name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Lint the code
      run: npm run lint || echo "No linter configured"

    - name: Build Docker image
      run: docker build -t ${{ github.repository }} .

    # Use GitHub OAuth for Docker Hub login
    - name: Log in to Docker Hub using GitHub OAuth
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}  # Use the GitHub username
        token: ${{ secrets.DOCKER_TOKEN }}  # GitHub Personal Access Token (PAT) stored in secrets

    - name: Push Docker image
      run: |
        docker tag ${{ github.repository }} ${{ github.actor }}/${{ github.repository }}
        docker push ${{ github.actor }}/${{ github.repository }}
