name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/my-node-app
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Super-linter
      uses: super-linter/super-linter@v6.6.0  # x-release-please-version
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        IGNORE_GENERATED_FILES: true
        IGNORE_GITIGNORED_FILES: true
        VALIDATE_ALL_CODEBASE: false
      continue-on-error: true
      

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push $IMAGE_NAME

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform (auto approve)
      run: terraform apply -auto-approve -var="docker_username=${{ secrets.DOCKER_USERNAME }}"
      
